### ISSUE TITLE
Setup of new Accounts

### ISSUE THREAD

**Issue by kingargyle** [KevBelisle/Rebel-Leagues#54]
I've managed to get this at least running locally but running into a couple of problems.

1. It would be helpful to know for the test data what the passwords are for the Administrators accounts and test player accounts.

2. If an error occurs the application doesn't seem to log anything to the standard PHP error log output, it just seems to swallow it.

I did manage to create the necessary db_access.php configuration file so I think I have the DB access setup right.   And I did run the DB script to get the tables and views setup.   Any additional information on getting this working so I can demo it to Ed Horne at our league meeting would be appreciated.

**Comment by KevBelisle** [comment]
Hi! I'm at work and don't remember what the test passwords were. However, you can generate new ones easily enough. The hash used for passwords is:

`hash('sha512', $_POST['password'].$dbUser['salt'])`

You can use this little website to do for you: http://www.miniwebtool.com/sha512-hash-generator/

If you put in "passwordSALT", it should give you "9aff79e5a2...c585".

Just use this to insert the user into the admin table:
`INSERT INTO admins (admin_id, username, password, salt, tier) VALUES (4, "Username", "9aff79e5a2...c585", "SALT", 1);`

**Comment by KevBelisle** [comment]
On file that it seems hasn't been included in the Git repo is a `.htaccess` file in the `api` directory.

Here's a copy of the .htaccess file that I use on my host:
`Options -MultiViews
AddDefaultCharset UTF-8
AddHandler x-mapp-php6 .php

RewriteBase /

RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond $1#%{REQUEST_URI} ([^#]*)#(.*?)\1$
RewriteRule ^(.*)\?*$ %2index.php?__route__=/$1 [L,QSA]`

**Comment by kingargyle** [comment]
Thanks, I'll try making some changes locally and see if I can get things working.

**Comment by kingargyle** [comment]
Okay a little more digging, looks like I'm getting 404 errors.  So suspect it has to do something with the rule rewriting.  Let me check my apache configuration.   I get these errors anytime I submit I try to submit a form on the admin pages.

**Comment by kingargyle** [comment]
Alright after some additional searching.  For a Mac using the local Sites option and configuration.  You need to edit the username.conf file, and add:

AllowOverrides All

To the entry.  Also needed to change the .htaccess base to point to the correct path for the api directory.  Once this was done, I was able to get some test players added to the app.
